train_BSIF=[Train_All_Data_DigiBSIF(:,1:916 ) Train_All_Data_DigiBSIF(:,1016:1916) Train_All_Data_SageBSIF(:,1:916 ) Train_All_Data_SageBSIF(:,1016:1916 )]*10^8;
trainlabel_BSIF=[Train_All_Label_DigiBSIF(:,1:916) Train_All_Label_DigiBSIF(:,1016:1916) Train_All_Label_SageBSIF(:,1:916) Train_All_Label_SageBSIF(:,1016:1916)];
testBSIF=[Test_All_Data_DigiBSIF Test_All_Data_SageBSIF]*10^8;
testlabelBSIF=[Test_All_Label_DigiBSIF Test_All_Label_SageBSIF];

hiddenSize1 =100;
autoenc1 = trainAutoencoder(train_BSIF,hiddenSize1, ...
    'MaxEpochs',100, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',3, ...
    'SparsityProportion',0.4, ...
    'ScaleData', false);
plotWeights(autoenc1);
feat1 = encode(autoenc1,train_BSIF);
hiddenSize2 = 100;
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
    'MaxEpochs',100, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.4, ...
    'ScaleData', false);
plotWeights(autoenc2);
feat2 = encode(autoenc2,feat1);

softnet = trainSoftmaxLayer(feat2,trainlabel_BSIF,'MaxEpochs',100);
deepnet = stack(autoenc1,autoenc2,softnet);
deepnet = train(deepnet,train_BSIF,trainlabel_BSIF);

ytrain = deepnet(train_BSIF);
ytest = deepnet(testBSIF);
ezroc3new(ytest,testlabelBSIF,2,'',1);