train_LBP=[Train_All_Data_DigiLBP(:,1:916 ) Train_All_Data_DigiLBP(:,1016:1916) Train_All_Data_SageLBP(:,1:916 ) Train_All_Data_SageLBP(:,1016:1916 )];
trainlabel_LBP=[Train_All_Label_DigiLBP(:,1:916) Train_All_Label_DigiLBP(:,1016:1916) Train_All_Label_SageLBP(:,1:916) Train_All_Label_SageLBP(:,1016:1916)];
testLBP=[Test_All_Data_DigiLBP Test_All_Data_SageLBP];
testlabelLBP=[Test_All_Label_DigiLBP Test_All_Label_SageLBP];

hiddenSize1 =100;
autoenc1 = trainAutoencoder(train_LBP,hiddenSize1, ...
    'MaxEpochs',100, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',3, ...
    'SparsityProportion',0.4, ...
    'ScaleData', false);
plotWeights(autoenc1);
feat1 = encode(autoenc1,train_LBP);
% hiddenSize2 = 100;
% autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
%     'MaxEpochs',200, ...
%     'L2WeightRegularization',0.008, ...
%     'SparsityRegularization',1, ...
%     'SparsityProportion',0.8, ...
%     'ScaleData', false);
% plotWeights(autoenc2);
% feat2 = encode(autoenc2,feat1);

softnet = trainSoftmaxLayer(feat1,trainlabel_LBP,'MaxEpochs',100);
deepnet = stack(autoenc1,softnet);
deepnet = train(deepnet,train_LBP,trainlabel_LBP);

ytrain = deepnet(train_LBP);
ytest = deepnet(testLBP);
ezroc3new(ytest,testlabelLBP,2,'',1);